name: Build Container

on:
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'
  workflow_run:
    workflows: ["SonarQube Analysis"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building the project"

      - name: Build for stage
        run: echo "Building the project for stage"